const STATUS_TONE = {
  COMPLETED: "success",
  CAN_FULFILL: "success",
  ACTIVE: "success",
  ORDERED: "success",
  "FULLY DELIVERED": "success",
  PROCESSED: "success",
  CONNECTED: "success",
  VERIFIED: "success",
  VALID: "success",
  SUCCESS: "success",
  COMPLETE: "success",
  MATCHED: "success",
  EXTRA_SUPPLY: "warning",
  SHORT_SUPPLY: "danger",
  MISSING_PART: "danger",
  UNEXPECTED_PART: "warning",
  COMPLETED_WITH_ERRORS: "warning",
  PARTIAL: "warning",
  AWAITING_CONFIRMATION: "warning",
  "PARTIALLY DELIVERED": "warning",
  PROCESSED_WITH_ERRORS: "warning",
  NEEDS_REVIEW: "warning",
  NOT_VERIFIED: "warning",
  PROCESSING: "info",
  PENDING: "info",
  SELECTED: "info",
  RECEIVED: "info",
  SKIPPED_DUPLICATE: "neutral",
  SUPERSEDED: "neutral",
  CANCELLED: "neutral",
  UNSUPPORTED: "neutral",
  NOT_CONFIGURED: "neutral",
  UNTESTED: "neutral",
  NO_ATTEMPTS_YET: "neutral",
  DISABLED: "neutral",
  FAILED: "danger",
  UNFULFILLED: "danger",
  "NOT DELIVERED": "danger",
  NOT_DELIVERED: "danger",
  INVALID: "danger",
  DOWNLOAD_FAILED: "danger",
};

export function StatusPill({ status }) {
  const tone = STATUS_TONE[status] || "neutral";
  const label = String(status || "-").replaceAll("_", " ");
  return <span className={`pill pill--${tone}`}>{label}</span>;
}
